USE test_db;

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post (
  id INT AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  userId INT NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_user_post FOREIGN KEY (userId) REFERENCES user (id)
);
